## Decision Tree Regressor
### Problem Statement: Build the model that predicts the Power Energy generated by the powerplant by taking atmosperic pressure, tempreture, vaccum and humidity into consideration.

### Data Gatherring

In [11]:
import pandas as pd 
path = r"https://raw.githubusercontent.com/onkar-satpute/Datasets/refs/heads/main/PowerPlant.csv"
df = pd.read_csv(path)
df.head()

      AT      V       AP     RH      PE
0   8.34  40.77  1010.84  90.01  480.48
1  23.64  58.49  1011.40  74.20  445.75
2  29.74  56.90  1007.15  41.91  438.76
3  19.07  49.69  1007.22  76.79  453.09
4  11.80  40.66  1017.13  97.20  464.43

### Perform data quality checks

In [12]:
df.shape

(9568, 5)

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9568 entries, 0 to 9567
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   AT      9568 non-null   float64
 1   V       9568 non-null   float64
 2   AP      9568 non-null   float64
 3   RH      9568 non-null   float64
 4   PE      9568 non-null   float64
dtypes: float64(5)
memory usage: 373.9 KB

In [14]:
# check for duplicated information
df.duplicated().sum()

np.int64(41)

In [15]:
# drop the duplicates
df = df.drop_duplicates()

In [16]:
#check for the missing data
df.isna().sum()

AT    0
V     0
AP    0
RH    0
PE    0
dtype: int64

### Separate the X and  Y features
#### X : atmospheric pressure, tempreture, vaccum and humidity
#### Y : Power Energy generated by the powerplant

In [22]:
X = df.drop(columns = ['PE'])
Y = df[['PE']]

In [23]:
X.head()

      AT      V       AP     RH
0   8.34  40.77  1010.84  90.01
1  23.64  58.49  1011.40  74.20
2  29.74  56.90  1007.15  41.91
3  19.07  49.69  1007.22  76.79
4  11.80  40.66  1017.13  97.20

In [24]:
Y.head()

       PE
0  480.48
1  445.75
2  438.76
3  453.09
4  464.43

### Data Cleaning and Data Preprocessing(Feature Scaling)