## Multiple Linear Regression
### Build a model that predicts the Profit of startups on basis of RND and MkT Amount

### Step 1: Data Gathering

In [3]:
import pandas as pd 
path = r"D:\3RI\Datasets-main\50_Startups.csv"
df = pd.read_csv(path)
df.head()

         RND      ADMIN        MKT       STATE     PROFIT
0  165349.20  136897.80  471784.10    New York  192261.83
1  162597.70  151377.59  443898.53  California  191792.06
2  153441.51  101145.55  407934.54     Florida  191050.39
3  144372.41  118671.85  383199.62    New York  182901.99
4  142107.34   91391.77  366168.42     Florida  166187.94

### Step 2: Data Quality Checks

In [4]:
df.shape

(50, 5)

In [10]:
df.columns

Index(['RND', 'ADMIN', 'MKT', 'STATE', 'PROFIT'], dtype='str')

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   RND     50 non-null     float64
 1   ADMIN   50 non-null     float64
 2   MKT     50 non-null     float64
 3   STATE   50 non-null     str
 4   PROFIT  50 non-null     float64
dtypes: float64(4), str(1)
memory usage: 2.1 KB

In [15]:
# Check for duplicates
df.duplicated().sum()

np.int64(0)

In [17]:
df = df.drop_duplicates()

In [18]:
# Check the missing data
df.isna().sum()

RND       0
ADMIN     0
MKT       0
STATE     0
PROFIT    0
dtype: int64

### Step 3: Seprate X and Y features
    Y : Target Feature , Dependent Feature => Profit
    X : Independent Feature => RND and MkT Amount

In [21]:
X = df[['RND', 'MKT']]
Y = df[['PROFIT']]

In [22]:
X.head()

         RND        MKT
0  165349.20  471784.10
1  162597.70  443898.53
2  153441.51  407934.54
3  144372.41  383199.62
4  142107.34  366168.42

In [23]:
Y.head()

      PROFIT
0  192261.83
1  191792.06
2  191050.39
3  182901.99
4  166187.94